<a href="https://colab.research.google.com/github/AnasTere/Data_Sci/blob/main/Tereschenko_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100): #displays 0-99 
    print(i)

In [ ]:
for i in range(5,8): #displays 3 values from 5-8 not including 8 
    print(i)

5
6
7


In [ ]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x):
    return x**2

In [ ]:
square(5)

In [ ]:
square(square(2))

16

In [ ]:
square(square(square(2)))


256

In [ ]:
square(123456)

15241383936

In [ ]:
square(square(5))

625

In [ ]:
def add_two(x):
    return x+2

In [ ]:
add_two(5)

7

In [ ]:
square(add_two(5))

49

### Logical Branching

In [ ]:
choice = "apple" #stores string apple in choice

In [ ]:
if choice == "apple": #demonstrates standard if statement 

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
choice = "orange" #changes choice to orange

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple"

In [ ]:
if choice == "apple": #demonstrates else if statement 

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") #how to get input from user

Please enter your choice (i.e. apple): oranges


In [ ]:
choice #displays choice

'oranges'

In [ ]:
if choice == "apple": #if loop considering input 

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


#### Coins

In [4]:
import numpy as np

In [5]:
np.random.random() #generates random number

0.27866224773236015

In [6]:
np.random.random() > 0.5 #checks if random number is greater than 0.5

False

In [7]:
def flip_coin(): #creates function flipcoin returns head or tails depending if random number is greater than o.5
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [ ]:
flip_coin()

### Graphics Output

In [2]:
from IPython.core.display import display, HTML

In [ ]:
display(HTML('<h1>Hello, world!</h1>'))

In [8]:
def coin():
  return np.random.randint(2) #returns either 0 or 1

In [10]:
coin()

0

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
show_img(heads)

In [ ]:
show_img(tails)

In [ ]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [ ]:
flip_coin()

In [ ]:
for i in range(5): #all of this just adds photos and gets either heads or tails
    flip_coin()

In [12]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

NameError: ignored

### Cards

In [14]:
def shuffle(x): 
    for i in range(len(x)-1,0,-1): #gives values for all spots in an array
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [15]:
a = np.arange(52) #makes array with 52 spots 

In [16]:
shuffle(a) #calls shuffle on array

array([44, 27,  3, 17, 21, 16, 29, 31, 43, 25,  5, 39,  9,  8, 26, 30, 28,
       38, 20, 35, 34, 18,  0,  2, 11, 22, 48, 49,  7, 24,  4, 36, 14,  1,
       23, 19, 50, 15, 12, 33, 37, 51, 42, 41, 46,  6, 47, 40, 13, 45, 10,
       32])

In [17]:
np.random.permutation(52) #creates new values in each space of array

array([45, 39, 48,  2, 10, 51,  4, 18,  9, 25, 27, 42, 17, 43, 14, 36, 24,
       40,  5,  0,  1, 44, 32, 22, 46,  7, 20, 29, 35, 21, 33,  3,  6, 49,
       26, 38, 50, 28,  8, 47, 12, 41, 15, 19, 23, 11, 34, 37, 13, 31, 16,
       30])

### Speed Test

In [18]:
%%timeit #shows how fast the function is, how efficent 
shuffle(a)

191 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
%%timeit
np.random.permutation(52) #shows hoe efficent the permutation call is 

3.52 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
import numpy as np

In [21]:
np.random.permutation(52)

array([11, 16, 17, 21, 41, 40, 22, 25, 31,  7, 26, 39, 33,  9, 32, 50, 23,
       37, 49, 48, 38, 42, 28, 43,  4, 34, 35, 36, 10, 46, 27, 45, 14, 29,
        6,  3,  0,  5, 15, 12, 30, 51, 24,  2, 18, 44,  1, 47, 19, 13,  8,
       20])

In [25]:
cards = np.random.permutation(52) #sets cards = to array of 52 in random order

In [26]:
cards #displays cards

array([40,  5, 26, 30,  8, 46, 47, 18, 15, 50, 43, 29, 25, 38, 13,  1, 10,
       41, 16,  2, 20, 27, 32, 34, 35, 51, 37, 12, 24,  9,  0, 44, 28, 42,
        7,  4, 36, 33, 17, 21, 11, 22, 31, 39,  6, 14, 45, 19, 48, 23,  3,
       49])

In [27]:
cards[0] #card at place 1

40

In [28]:
cards[1] #card at place 2

5

In [29]:
cards[2] #card at place 3

26

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [30]:
np.arange(52).reshape(4,13) #4 rows 13 columns 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [31]:
np.arange(52).reshape(4,13)%13 #makes all values go up to 12 from 0 by column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
np.arange(52).reshape(4,13)//13 #makes all values increase by row 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [33]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [34]:
def card_name(card_number): #finds card name and number depending on value.
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [35]:
card_name(0)

'Ace of Clubs'

In [36]:
card_name(51)

'King of Diamonds'

In [37]:
cards = np.random.permutation(52)

In [38]:
top_of_deck         = card_name(cards[0]) #first card place 1
second_card_in_deck = card_name(cards[1]) #second card place 2 
last_card_in_deck   = card_name(cards[-1]) #last card end of array

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [39]:
for i in range(5): #for loop loops through first 5 cards 
    print(card_name(cards[i]))

Six of Spades
Eight of Diamonds
Two of Diamonds
Ten of Spades
Queen of Clubs


In [ ]:
for i in range(15): #first 15 cards
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [40]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [41]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [54]:
i = np.random.randint(4) # random integer from 0-3
j = np.random.randint(13) #random integer from 0-12

In [48]:
i,j 

(2, 6)

In [55]:
suit[i]

'k'

In [ ]:
card[j]

'q'

In [56]:
from IPython.core.display import display, HTML

In [57]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [58]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [59]:
show_img(img) #displays actual playing card not just writing 

In [60]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [61]:
card_image(3)

'k4'

In [62]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) #displays all 52 cards in order 